apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-appset
  namespace: argocd

spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/curioos/gitops-repo
          revision: HEAD
          directories:
          - path: "*"

      - list:
          elements:
          - env: dev
            namespace: dev
          - env: prod
            namespace: prod

  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/curioos/gitops-repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

