apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app4-child
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/curioos/gitops-repo
    targetRevision: HEAD
    path: app4
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
